awk '
/^[ \t]*"shutdown"/ {
    print "        \"textDocument/rename\" => {"
    print "            if let Some(req_id) = id {"
    print "                let mut result = serde_json::Value::Null;"
    print "                if let Some(params) = msg.get(\"params\") {"
    print "                    if let (Some(uri), Some(pos), Some(new_name)) = ("
    print "                        params.get(\"textDocument\").and_then(|td| td.get(\"uri\")).and_then(|u| u.as_str()),"
    print "                        params.get(\"position\"),"
    print "                        params.get(\"newName\").and_then(|n| n.as_str())"
    print "                    ) {"
    print "                        let line = pos.get(\"line\").and_then(|l| l.as_u64()).unwrap_or(0) as u32;"
    print "                        let character = pos.get(\"character\").and_then(|c| c.as_u64()).unwrap_or(0) as u32;"
    print "                        "
    print "                        if let Some(text) = workspace.documents.get(uri) {"
    print "                            let offset = line_col_to_byte_offset(text, line, character);"
    print "                            if let Some(semantic) = workspace.semantics.get(uri) {"
    print "                                let mut target_def_span: Option<Span> = None;"
    print "                                for def_span in semantic.index.definitions.values() {"
    print "                                    if offset >= def_span.start && offset <= def_span.end {"
    print "                                        target_def_span = Some(*def_span);"
    print "                                        break;"
    print "                                    }"
    print "                                }"
    print "                                if target_def_span.is_none() {"
    print "                                    for (usage_span, def_span) in &semantic.index.usages {"
    print "                                        if offset >= usage_span.start && offset <= usage_span.end {"
    print "                                            target_def_span = Some(*def_span);"
    print "                                            break;"
    print "                                        }"
    print "                                    }"
    print "                                }"
    print "                                if let Some(def_span) = target_def_span {"
    print "                                    let mut changes = Vec::new();"
    print "                                    let (dl, dc) = byte_offset_to_line_col(text, def_span.start);"
    print "                                    let (del, dec) = byte_offset_to_line_col(text, def_span.end);"
    print "                                    changes.push(json!({"
    print "                                        \"range\": { \"start\": { \"line\": dl, \"character\": dc }, \"end\": { \"line\": del, \"character\": dec } },"
    print "                                        \"newText\": new_name"
    print "                                    }));"
    print "                                    for (usage_span, ds) in &semantic.index.usages {"
    print "                                        if ds.start == def_span.start && ds.end == def_span.end {"
    print "                                            let (sl, sc) = byte_offset_to_line_col(text, usage_span.start);"
    print "                                            let (el, ec) = byte_offset_to_line_col(text, usage_span.end);"
    print "                                            changes.push(json!({"
    print "                                                \"range\": { \"start\": { \"line\": sl, \"character\": sc }, \"end\": { \"line\": el, \"character\": ec } },"
    print "                                                \"newText\": new_name"
    print "                                            }));"
    print "                                        }"
    print "                                    }"
    print "                                    let mut uri_changes = serde_json::Map::new();"
    print "                                    uri_changes.insert(uri.to_string(), json!(changes));"
    print "                                    result = json!({ \"changes\": uri_changes });"
    print "                                }"
    print "                            }"
    print "                        }"
    print "                    }"
    print "                }"
    print "                send_response(json!({"
    print "                    \"jsonrpc\": \"2.0\","
    print "                    \"id\": req_id,"
    print "                    \"result\": result"
    print "                }));"
    print "            }"
    print "        }"
}
{ print }
' lsp/src/lib.rs > lsp/src/lib.rs.new && mv lsp/src/lib.rs.new lsp/src/lib.rs
